
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3PTECh
 */
public class adminDash extends javax.swing.JFrame {

    /**
     * Creates new form adminDash
     */
    public adminDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 44, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 102, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 255));
        jButton6.setText("NOTIFICATIONS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jButton11.setBackground(new java.awt.Color(204, 51, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setText("LOGOUT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTabbedPane3.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane3.setOpaque(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("SEARCH");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 14, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 14, 193, -1));

        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("USERNAME");
        jDesktopPane2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 354, -1, -1));

        jLabel3.setText("PASSWORD");
        jDesktopPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 354, -1, -1));

        jLabel7.setText("EMAIL");
        jDesktopPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 354, -1, -1));

        jLabel8.setText("FULL NAME");
        jDesktopPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 354, -1, -1));

        jLabel9.setText("SEX");
        jDesktopPane2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 354, -1, -1));

        jLabel10.setText("PHONE");
        jDesktopPane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 354, -1, -1));
        jDesktopPane2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 376, 94, -1));
        jDesktopPane2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 376, 92, -1));
        jDesktopPane2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 376, 112, -1));
        jDesktopPane2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 376, 125, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", " " }));
        jDesktopPane2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 376, -1, -1));
        jDesktopPane2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 376, 100, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 435, -1, -1));

        jLabel11.setText("ID");
        jDesktopPane2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 354, -1, -1));
        jDesktopPane2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 376, 29, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 464, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 464, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "USERNAME", "PASSWORD", "EMAIL", "FULL NAME", "SEX", "PHONE NUMBER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 690, 144));

        jLabel6.setText("ALL USERS");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jDesktopPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel3.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 530));

        jTabbedPane3.addTab("", jPanel3);

        jTabbedPane1.addTab("MANAGE USERS", jTabbedPane3);

        jDesktopPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jDesktopPane4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 670, 240));
        jDesktopPane4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 51));
        jButton8.setText("SEARCH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jButton7.setBackground(new java.awt.Color(102, 102, 0));
        jButton7.setForeground(new java.awt.Color(204, 255, 255));
        jButton7.setText("VIEW ALL BUDGET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDesktopPane4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jButton10.setBackground(new java.awt.Color(153, 51, 0));
        jButton10.setText("EDIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDesktopPane4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\3PTECh\\Documents\\NetBeansProjects\\trackMeIcome\\src\\main\\java\\icons\\digital-digital-art-black-background-graphic-design-1921697-wallhere.com.jpg")); // NOI18N
        jDesktopPane4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane5.addTab("MANAGE BUDGET", jDesktopPane4);

        jTabbedPane1.addTab("EDIT BUDGET", jTabbedPane5);

        jTabbedPane4.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane4.setOpaque(true);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "LOG ID", "USER", "LOGS", "TIME", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jDesktopPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 34, 680, 360));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\3PTECh\\Documents\\NetBeansProjects\\trackMeIcome\\src\\main\\java\\icons\\digital-digital-art-black-background-graphic-design-1921697-wallhere.com.jpg")); // NOI18N
        jDesktopPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jTabbedPane4.addTab("ACTIVITY HISTORY", jPanel4);

        jTabbedPane1.addTab("ACTIVITY", jTabbedPane4);

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("BACKUP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 43, -1, -1));

        jButton5.setText("RESTORE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 43, 97, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel13)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel13)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 112, -1, -1));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\3PTECh\\Documents\\NetBeansProjects\\trackMeIcome\\src\\main\\java\\icons\\digital-digital-art-black-background-graphic-design-1921697-wallhere.com.jpg")); // NOI18N
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane2.addTab("BACKUP", jPanel5);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL REGISTERED CLIENTS");

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jDesktopPane3.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("RECORDS", jDesktopPane3);

        jTabbedPane1.addTab("DATA", jTabbedPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         comm commForm = new comm();
    commForm.setVisible(true);   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        //activity
        DefaultTableModel model = new DefaultTableModel(new String[]{"User ID", "Activity", "Timestamp", "Description"}, 0);
        String sql = "SELECT user_id, activity, timestamp, details FROM user_activity_logs";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                int userId = rs.getInt("user_id");
                String activity = rs.getString("activity");
                Timestamp timestamp = rs.getTimestamp("timestamp");
                String details = rs.getString("details");

                model.addRow(new Object[]{userId, activity, timestamp, details});
            }
            jTable2.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  jLabel13.setText("Database Backup Successfully");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Get the selected row index from jTable1
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            // No row is selected
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
            return;
        }

        // Retrieve the user_id from the selected row
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int userId = (int) model.getValueAt(selectedRow, 0); // Assuming user_id is in the first column

        // SQL query to delete the row from the users table
        String sql = "DELETE FROM users WHERE user_id = ?";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            PreparedStatement pstmt = connection.prepareStatement(sql)) {
            // Set the user_id parameter for the SQL query
            pstmt.setInt(1, userId);

            // Execute the delete query
            int rowsAffected = pstmt.executeUpdate();

            // Check if the row was successfully deleted
            if (rowsAffected > 0) {
                // Remove the selected row from the table model
                model.removeRow(selectedRow);

                // Show a confirmation message
                JOptionPane.showMessageDialog(null, "User deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete user.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle potential SQL exceptions
            JOptionPane.showMessageDialog(null, "Error deleting user: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Retrieve data from input fields
        String username = jTextField2.getText();
        String password = jTextField3.getText();
        String email = jTextField4.getText();
        String fullName = jTextField5.getText();
        String sex = jComboBox1.getSelectedItem().toString();
        String phoneNumber = jTextField6.getText();

        // SQL query to insert data into the users table
        String sql = "INSERT INTO users (username, password, email, full_name, sex, phone_number) VALUES (?, ?, ?, ?, ?, ?)";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            PreparedStatement pstmt = connection.prepareStatement(sql)) {
            // Set parameters for the SQL query
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.setString(3, email);
            pstmt.setString(4, fullName);
            pstmt.setString(5, sex);
            pstmt.setString(6, phoneNumber);

            // Execute the insert query
            int rowsAffected = pstmt.executeUpdate();

            // Show a success message
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "User details saved successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to save user details.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle potential SQL exceptions
            JOptionPane.showMessageDialog(null, "Error saving user details: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Retrieve data from input fields
        String username = jTextField7.getText();
        String password = jTextField2.getText();
        String email = jTextField3.getText();
        String fullName = jTextField4.getText();
        String sex = jComboBox1.getSelectedItem().toString();
        String phoneNumber = jTextField5.getText();

        // Retrieve the user_id from the table selection
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a user to update.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int userId = (int) model.getValueAt(selectedRow, 0); // Assuming user_id is in the first column

        // SQL query to update the users table
        String sql = "UPDATE users SET username = ?, password = ?, email = ?, full_name = ?, sex = ?, phone_number = ? WHERE user_id = ?";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            PreparedStatement pstmt = connection.prepareStatement(sql)) {
            // Set parameters for the SQL query
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.setString(3, email);
            pstmt.setString(4, fullName);
            pstmt.setString(5, sex);
            pstmt.setString(6, phoneNumber);
            pstmt.setInt(7, userId);

            // Execute the update query
            int rowsAffected = pstmt.executeUpdate();

            // Show a success message
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "User details updated successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "No changes were made.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle potential SQL exceptions
            JOptionPane.showMessageDialog(null, "Error updating user details: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // SQL query to retrieve all fields from the users table
        String sql = "SELECT * FROM users";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(sql)) {

            // Get the table model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Clear existing rows

            // Define column names (matching the users table schema)
            String[] columnNames = {"user_id", "username", "password", "email", "full_name", "sex", "phone_number"};
            model.setColumnIdentifiers(columnNames);

            // Populate the table with result set data
            while (rs.next()) {
                Object[] row = new Object[columnNames.length];
                row[0] = rs.getInt("user_id");
                row[1] = rs.getString("username");
                row[2] = rs.getString("password");
                row[3] = rs.getString("email");
                row[4] = rs.getString("full_name");
                row[5] = rs.getString("sex");
                row[6] = rs.getString("phone_number");
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle potential SQL exceptions
            JOptionPane.showMessageDialog(null, "Error retrieving user data: " + e.getMessage());
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // Retrieve email from jTextField1
        String email = jTextField1.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter an email address.");
            return;
        }

        // SQL query to find user with the matching email
        String sql = "SELECT * FROM users WHERE email = ?";

        MyDataConnect dbConnect = new MyDataConnect();
        try (Connection connection = dbConnect.getConnection();
            PreparedStatement pstmt = connection.prepareStatement(sql)) {
            // Set the email parameter for the SQL query
            pstmt.setString(1, email);

            // Execute the query
            try (ResultSet rs = pstmt.executeQuery()) {
                // Create or update the table model
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows

                // Define column names based on the users table schema
                String[] columnNames = {"user_id", "username", "password", "email", "full_name", "sex", "phone_number"};
                model.setColumnIdentifiers(columnNames);

                // Populate the table with result set data
                if (rs.next()) {
                    Object[] row = new Object[columnNames.length];
                    row[0] = rs.getInt("user_id");
                    row[1] = rs.getString("username");
                    row[2] = rs.getString("password");
                    row[3] = rs.getString("email");
                    row[4] = rs.getString("full_name");
                    row[5] = rs.getString("sex");
                    row[6] = rs.getString("phone_number");
                    model.addRow(row);
                } else {
                    JOptionPane.showMessageDialog(null, "No user found with the provided email.");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle potential SQL exceptions
            JOptionPane.showMessageDialog(null, "Error retrieving user information: " + e.getMessage());
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
       try {
            Overview overview = new Overview();
            int userCount = overview.countNonAdminUsers();
            jLabel12.setText("" + userCount);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error retrieving user count: " + e.getMessage());
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      // Fetch data from budget table and display in jTable4
    String sql = "SELECT * FROM budget";
    MyDataConnect dbConnect = new MyDataConnect();

    try (Connection connection = dbConnect.getConnection();
         PreparedStatement pstmt = connection.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {

        // Get metadata to create table model
        ResultSetMetaData rsmd = rs.getMetaData();
        int columnCount = rsmd.getColumnCount();

        // Create table model and set column names
        DefaultTableModel tableModel = new DefaultTableModel();
        for (int i = 1; i <= columnCount; i++) {
            tableModel.addColumn(rsmd.getColumnName(i));
        }

        // Add rows to table model
        while (rs.next()) {
            Object[] rowData = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                rowData[i - 1] = rs.getObject(i);
            }
            tableModel.addRow(rowData);
        }

        // Set model to jTable4
        jTable4.setModel(tableModel);

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Retrieve email from jTextField8
    String email = jTextField8.getText().trim();

    // Validate email input
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an email.");
        return;
    }

    // Initialize database connection
    MyDataConnect dbConnect = new MyDataConnect();
    Connection connection = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        connection = dbConnect.getConnection();

        // Query to get user_id from users table
        String userQuery = "SELECT user_id FROM users WHERE email = ?";
        pstmt = connection.prepareStatement(userQuery);
        pstmt.setString(1, email);
        rs = pstmt.executeQuery();

        if (rs.next()) {
            int userId = rs.getInt("user_id");

            // Query to fetch budget details using user_id
            String budgetQuery = "SELECT * FROM budget WHERE user_id = ?";
            pstmt = connection.prepareStatement(budgetQuery);
            pstmt.setInt(1, userId);
            rs = pstmt.executeQuery();

            // Get metadata to create table model
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // Create table model and set column names
            DefaultTableModel tableModel = new DefaultTableModel();
            for (int i = 1; i <= columnCount; i++) {
                tableModel.addColumn(rsmd.getColumnName(i));
            }

            // Add rows to table model
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                tableModel.addRow(rowData);
            }

            // Set model to jTable4
            jTable4.setModel(tableModel);

        } else {
            JOptionPane.showMessageDialog(this, "No user found with the provided email.");
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        ex.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (connection != null) connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         jLabel13.setText("Database Restored Successfully");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 
     
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
